/**
 * AI Recipe Detail — shows a recipe generated by BiteSwipe AI from scanned ingredients,
 * with thumbs-up/down + 5-star rating feedback at the bottom.
 */
import React, { useMemo, useState } from 'react';
import { StyleSheet, Text, View, ScrollView, TouchableOpacity, Alert, Platform } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { BrandColors, Gradients, Radius, Spacing, Typography } from '@/constants/theme';

type Liked = 'yes' | 'no' | null;

export default function AIRecipeScreen() {
  const router = useRouter();
  const { recipe } = useLocalSearchParams<{ recipe?: string }>();

  const data = useMemo(() => {
    try { return recipe ? JSON.parse(recipe) : null; } catch { return null; }
  }, [recipe]);

  const [liked, setLiked] = useState<Liked>(null);
  const [stars, setStars] = useState(0);
  const [submitted, setSubmitted] = useState(false);

  if (!data) {
    return (
      <View style={[s.screen, { alignItems: 'center', justifyContent: 'center' }]}>
        <Text style={{ color: BrandColors.textSecondary }}>Recipe data missing.</Text>
        <TouchableOpacity onPress={() => router.back()} style={{ marginTop: 16 }}>
          <Text style={{ color: BrandColors.primaryStart }}>Go back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const submitFeedback = () => {
    setSubmitted(true);
    const msg = liked === 'yes'
      ? `Thanks! Glad you loved "${data.title}".`
      : liked === 'no'
      ? `Got it — we'll learn from this and suggest better next time.`
      : `Thanks for your feedback!`;
    if (Platform.OS === 'web') window.alert(msg);
    else Alert.alert('Thank you!', msg);
  };

  return (
    <View style={s.screen}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}>
        <View style={s.header}>
          <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
            <Feather name="arrow-left" size={22} color={BrandColors.textPrimary} />
          </TouchableOpacity>
          <View style={s.aiPill}>
            <Feather name="zap" size={12} color="#fff" />
            <Text style={s.aiPillT}>BiteSwipe AI</Text>
          </View>
        </View>

        <Text style={s.title}>{data.title}</Text>
        <Text style={s.cuisine}>{data.cuisine} • {data.difficulty}</Text>

        <View style={s.stats}>
          <View style={s.stat}>
            <Feather name="clock" size={16} color={BrandColors.primaryStart} />
            <Text style={s.statT}>{data.cookTime}</Text>
          </View>
          <View style={s.stat}>
            <Feather name="zap" size={16} color={BrandColors.primaryStart} />
            <Text style={s.statT}>{data.calories} cal</Text>
          </View>
          <View style={s.stat}>
            <Feather name="users" size={16} color={BrandColors.primaryStart} />
            <Text style={s.statT}>{data.servings} servings</Text>
          </View>
        </View>

        {Array.isArray(data.tags) && data.tags.length > 0 && (
          <View style={s.tagRow}>
            {data.tags.map((t: string, i: number) => (
              <View key={i} style={s.tag}><Text style={s.tagT}>{t}</Text></View>
            ))}
          </View>
        )}

        <Text style={s.sectionTitle}>Ingredients</Text>
        <View style={s.list}>
          {(data.ingredients ?? []).map((ing: string, i: number) => (
            <View key={i} style={s.ingItem}>
              <Feather name="check-circle" size={16} color={BrandColors.success} />
              <Text style={s.ingText}>{ing}</Text>
            </View>
          ))}
        </View>

        <Text style={s.sectionTitle}>Instructions</Text>
        <View style={s.stepList}>
          {(data.steps ?? []).map((step: string, i: number) => (
            <View key={i} style={s.stepItem}>
              <View style={s.stepNum}><Text style={s.stepNumT}>{i + 1}</Text></View>
              <Text style={s.stepText}>{step}</Text>
            </View>
          ))}
        </View>

        {/* Feedback widget */}
        <View style={s.feedback}>
          <Text style={s.fbTitle}>Did you like it?</Text>
          <View style={s.thumbsRow}>
            <TouchableOpacity
              onPress={() => setLiked('yes')}
              style={[s.thumbBtn, liked === 'yes' && s.thumbBtnActive]}
              activeOpacity={0.8}
            >
              <Feather name="thumbs-up" size={20} color={liked === 'yes' ? '#fff' : BrandColors.textPrimary} />
              <Text style={[s.thumbT, liked === 'yes' && { color: '#fff' }]}>Loved it</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setLiked('no')}
              style={[s.thumbBtn, liked === 'no' && s.thumbBtnActiveNo]}
              activeOpacity={0.8}
            >
              <Feather name="thumbs-down" size={20} color={liked === 'no' ? '#fff' : BrandColors.textPrimary} />
              <Text style={[s.thumbT, liked === 'no' && { color: '#fff' }]}>Not for me</Text>
            </TouchableOpacity>
          </View>

          <Text style={s.fbSub}>Rate this recipe</Text>
          <View style={s.starsRow}>
            {[1, 2, 3, 4, 5].map(n => (
              <TouchableOpacity key={n} onPress={() => setStars(n)} activeOpacity={0.7}>
                <Feather
                  name="star"
                  size={32}
                  color={n <= stars ? BrandColors.accent : BrandColors.textTertiary}
                  style={{ marginHorizontal: 4 }}
                />
              </TouchableOpacity>
            ))}
          </View>

          <TouchableOpacity
            onPress={submitFeedback}
            disabled={submitted || (liked === null && stars === 0)}
            activeOpacity={0.85}
          >
            <LinearGradient
              colors={submitted ? ['#444', '#666'] : Gradients.primary as [string, string]}
              start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
              style={s.fbBtn}
            >
              <Feather name={submitted ? 'check' : 'send'} size={16} color="#fff" style={{ marginRight: 8 }} />
              <Text style={s.fbBtnT}>{submitted ? 'Feedback sent' : 'Submit feedback'}</Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BrandColors.dark900 },
  scroll: { padding: Spacing.lg, paddingTop: Spacing.xl, paddingBottom: Spacing.xxl },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md, marginTop: Spacing.lg },
  backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: BrandColors.glass, borderWidth: 1, borderColor: BrandColors.glassBorder, alignItems: 'center', justifyContent: 'center' },
  aiPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: BrandColors.primaryStart, paddingHorizontal: 10, paddingVertical: 5, borderRadius: Radius.full },
  aiPillT: { color: '#fff', fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
  title: { color: BrandColors.textPrimary, ...Typography.h1, marginBottom: 4 },
  cuisine: { color: BrandColors.textSecondary, ...Typography.body, marginBottom: Spacing.md },
  stats: { flexDirection: 'row', gap: Spacing.lg, marginBottom: Spacing.md, backgroundColor: BrandColors.dark800, padding: Spacing.md, borderRadius: Radius.lg },
  stat: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  statT: { color: BrandColors.textPrimary, ...Typography.bodyBold },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: Spacing.md },
  tag: { backgroundColor: BrandColors.glass, borderWidth: 1, borderColor: BrandColors.glassBorder, paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.full },
  tagT: { color: BrandColors.textSecondary, fontSize: 11, fontWeight: '600' },
  sectionTitle: { color: BrandColors.textPrimary, ...Typography.h2, marginBottom: Spacing.sm, marginTop: Spacing.lg },
  list: { gap: Spacing.sm },
  ingItem: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  ingText: { color: BrandColors.textSecondary, ...Typography.body, flex: 1 },
  stepList: { gap: Spacing.lg },
  stepItem: { flexDirection: 'row', gap: Spacing.md },
  stepNum: { width: 28, height: 28, borderRadius: 14, backgroundColor: BrandColors.dark600, alignItems: 'center', justifyContent: 'center' },
  stepNumT: { color: BrandColors.primaryStart, fontWeight: '800' },
  stepText: { color: BrandColors.textSecondary, ...Typography.body, flex: 1, lineHeight: 22 },
  feedback: { marginTop: Spacing.xxl, padding: Spacing.lg, backgroundColor: BrandColors.dark800, borderRadius: Radius.lg, borderWidth: 1, borderColor: BrandColors.glassBorder },
  fbTitle: { color: BrandColors.textPrimary, ...Typography.h3, marginBottom: Spacing.md, textAlign: 'center' },
  fbSub: { color: BrandColors.textSecondary, ...Typography.caption, marginTop: Spacing.lg, marginBottom: Spacing.xs, textAlign: 'center' },
  thumbsRow: { flexDirection: 'row', gap: Spacing.sm, justifyContent: 'center' },
  thumbBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, backgroundColor: BrandColors.dark600, borderRadius: Radius.full, borderWidth: 1, borderColor: BrandColors.glassBorder },
  thumbBtnActive: { backgroundColor: BrandColors.success, borderColor: BrandColors.success },
  thumbBtnActiveNo: { backgroundColor: '#A03030', borderColor: '#A03030' },
  thumbT: { color: BrandColors.textPrimary, ...Typography.bodyBold, fontSize: 13 },
  starsRow: { flexDirection: 'row', justifyContent: 'center', marginVertical: Spacing.sm },
  fbBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: Spacing.md, borderRadius: Radius.full, marginTop: Spacing.md },
  fbBtnT: { color: '#fff', ...Typography.bodyBold },
});
