/**
 * AI Recipe Detail — shows a recipe generated by BiteSwipe AI from scanned ingredients,
 * with thumbs-up/down + 5-star rating feedback at the bottom.
 */
import React, { useEffect, useMemo, useState } from 'react';
import { StyleSheet, Text, View, ScrollView, TouchableOpacity, Alert, Platform } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { BrandColors, Gradients, Radius, Spacing, Typography } from '@/constants/theme';
import { isRecipeSaved, saveRecipe, unsaveRecipe } from '@/services/savedRecipes';
import { addItems, missingFromPantry } from '@/services/shoppingList';

type Liked = 'yes' | 'no' | null;

export default function AIRecipeScreen() {
  const router = useRouter();
  const { recipe } = useLocalSearchParams<{ recipe?: string }>();

  const data = useMemo(() => {
    try { return recipe ? JSON.parse(recipe) : null; } catch { return null; }
  }, [recipe]);

  const [liked, setLiked] = useState<Liked>(null);
  const [stars, setStars] = useState(0);
  const [submitted, setSubmitted] = useState(false);
  const [checkedSteps, setCheckedSteps] = useState<Set<number>>(new Set());
  const [bookmarked, setBookmarked] = useState(false);
  const [bookmarkBusy, setBookmarkBusy] = useState(false);

  useEffect(() => {
    if (!data?.id) return;
    (async () => { setBookmarked(await isRecipeSaved(data.id)); })();
  }, [data?.id]);

  const toggleBookmark = () => {
    if (!data?.id || bookmarkBusy) return;
    const next = !bookmarked;
    setBookmarked(next);
    setBookmarkBusy(true);
    const op = next
      ? saveRecipe({
          id: data.id,
          title: data.title,
          cuisine: data.cuisine,
          cookTime: data.cookTime,
          difficulty: data.difficulty,
          calories: data.calories,
          servings: data.servings,
          ingredients: data.ingredients,
          steps: data.steps,
          tags: data.tags,
          matchPercentage: data.matchPercentage,
          source: 'ai',
        })
      : unsaveRecipe(data.id);
    op.catch((e: any) => {
      console.warn('[ai-recipe save]', e);
      setBookmarked(!next);
      const msg = e?.message ?? 'Could not update saved.';
      if (Platform.OS === 'web') window.alert(msg);
      else Alert.alert('Error', msg);
    }).finally(() => setBookmarkBusy(false));
  };

  const startCooking = () => {
    if (!data) return;
    router.push({
      pathname: '/cook-mode',
      params: {
        title: data.title,
        steps: JSON.stringify(data.steps ?? []),
        recipeId: data.id,
        source: 'ai',
      },
    });
  };

  const handleAddToShoppingList = async () => {
    if (!data?.ingredients?.length) return;
    const missing = await missingFromPantry(data.ingredients);
    const toAdd = missing.length > 0 ? missing : data.ingredients;
    const added = await addItems(toAdd, data.title);
    const msg = added > 0
      ? `Added ${added} item${added === 1 ? '' : 's'} to your shopping list.`
      : 'Everything in this recipe is already on your list.';
    if (Platform.OS === 'web') window.alert(msg);
    else Alert.alert('Shopping list', msg);
  };

  const toggleStep = (i: number) =>
    setCheckedSteps(prev => {
      const next = new Set(prev);
      next.has(i) ? next.delete(i) : next.add(i);
      return next;
    });

  const totalSteps: number = (data?.steps ?? []).length;
  const doneCount = checkedSteps.size;

  if (!data) {
    return (
      <View style={[s.screen, { alignItems: 'center', justifyContent: 'center' }]}>
        <Text style={{ color: BrandColors.textSecondary }}>Recipe data missing.</Text>
        <TouchableOpacity onPress={() => router.back()} style={{ marginTop: 16 }}>
          <Text style={{ color: BrandColors.primaryStart }}>Go back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const submitFeedback = () => {
    setSubmitted(true);
    const msg = liked === 'yes'
      ? `Thanks! Glad you loved "${data.title}".`
      : liked === 'no'
      ? `Got it — we'll learn from this and suggest better next time.`
      : `Thanks for your feedback!`;
    if (Platform.OS === 'web') window.alert(msg);
    else Alert.alert('Thank you!', msg);
  };

  return (
    <View style={s.screen}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}>
        <View style={s.header}>
          <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
            <Feather name="arrow-left" size={22} color={BrandColors.textPrimary} />
          </TouchableOpacity>
          <View style={s.aiPill}>
            <Feather name="zap" size={12} color="#fff" />
            <Text style={s.aiPillT}>BiteSwipe AI</Text>
          </View>
          <TouchableOpacity onPress={toggleBookmark} disabled={bookmarkBusy} style={s.bookmarkBtn} activeOpacity={0.75}>
            <Feather
              name="bookmark"
              size={20}
              color={bookmarked ? BrandColors.primaryStart : BrandColors.textPrimary}
            />
          </TouchableOpacity>
        </View>

        <Text style={s.title}>{data.title}</Text>
        <Text style={s.cuisine}>{data.cuisine} • {data.difficulty}</Text>

        <View style={s.stats}>
          <View style={s.stat}>
            <Feather name="clock" size={16} color={BrandColors.primaryStart} />
            <Text style={s.statT}>{data.cookTime}</Text>
          </View>
          <View style={s.stat}>
            <Feather name="zap" size={16} color={BrandColors.primaryStart} />
            <Text style={s.statT}>{data.calories} cal</Text>
          </View>
          <View style={s.stat}>
            <Feather name="users" size={16} color={BrandColors.primaryStart} />
            <Text style={s.statT}>{data.servings} servings</Text>
          </View>
        </View>

        {Array.isArray(data.tags) && data.tags.length > 0 && (
          <View style={s.tagRow}>
            {data.tags.map((t: string, i: number) => (
              <View key={i} style={s.tag}><Text style={s.tagT}>{t}</Text></View>
            ))}
          </View>
        )}

        <Text style={s.sectionTitle}>Ingredients</Text>
        <View style={s.list}>
          {(data.ingredients ?? []).map((ing: string, i: number) => (
            <View key={i} style={s.ingItem}>
              <Feather name="check-circle" size={16} color={BrandColors.success} />
              <Text style={s.ingText}>{ing}</Text>
            </View>
          ))}
        </View>

        <TouchableOpacity onPress={handleAddToShoppingList} activeOpacity={0.85} style={s.shoppingBtn}>
          <Feather name="shopping-cart" size={16} color={BrandColors.primaryStart} style={{ marginRight: 8 }} />
          <Text style={s.shoppingBtnT}>Add missing to shopping list</Text>
        </TouchableOpacity>

        <View style={s.stepsTitleRow}>
          <Text style={s.sectionTitle}>Instructions</Text>
          {totalSteps > 0 && (
            <View style={s.progressPill}>
              {doneCount === totalSteps
                ? <Feather name="check-circle" size={13} color={BrandColors.success} />
                : <Text style={s.progressPillT}>{doneCount}/{totalSteps}</Text>}
            </View>
          )}
        </View>

        {totalSteps > 0 && (
          <View style={s.progressBar}>
            <View style={[s.progressFill, { width: `${(doneCount / totalSteps) * 100}%` as any }]} />
          </View>
        )}

        <View style={s.stepList}>
          {(data.steps ?? []).map((step: string, i: number) => {
            const done = checkedSteps.has(i);
            return (
              <TouchableOpacity
                key={i}
                onPress={() => toggleStep(i)}
                activeOpacity={0.75}
                style={[s.stepItem, done && s.stepItemDone]}
              >
                <View style={[s.stepCheck, done && s.stepCheckDone]}>
                  {done
                    ? <Feather name="check" size={14} color="#fff" />
                    : <Text style={s.stepNumT}>{i + 1}</Text>}
                </View>
                <Text style={[s.stepText, done && s.stepTextDone]}>{step}</Text>
              </TouchableOpacity>
            );
          })}
        </View>

        {doneCount === totalSteps && totalSteps > 0 && (
          <View style={s.allDoneBanner}>
            <Feather name="check-circle" size={18} color={BrandColors.success} />
            <Text style={s.allDoneT}>All steps done — enjoy your meal!</Text>
          </View>
        )}

        {totalSteps > 0 && (
          <TouchableOpacity onPress={startCooking} activeOpacity={0.85} style={{ marginTop: Spacing.lg }}>
            <LinearGradient colors={Gradients.primary as [string, string]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={s.cookBtn}>
              <Feather name="play-circle" size={20} color="#fff" style={{ marginRight: 8 }} />
              <Text style={s.cookBtnT}>Start guided cook</Text>
            </LinearGradient>
          </TouchableOpacity>
        )}

        {/* Feedback widget */}
        <View style={s.feedback}>
          <Text style={s.fbTitle}>Did you like it?</Text>
          <View style={s.thumbsRow}>
            <TouchableOpacity
              onPress={() => setLiked('yes')}
              style={[s.thumbBtn, liked === 'yes' && s.thumbBtnActive]}
              activeOpacity={0.8}
            >
              <Feather name="thumbs-up" size={20} color={liked === 'yes' ? '#fff' : BrandColors.textPrimary} />
              <Text style={[s.thumbT, liked === 'yes' && { color: '#fff' }]}>Loved it</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setLiked('no')}
              style={[s.thumbBtn, liked === 'no' && s.thumbBtnActiveNo]}
              activeOpacity={0.8}
            >
              <Feather name="thumbs-down" size={20} color={liked === 'no' ? '#fff' : BrandColors.textPrimary} />
              <Text style={[s.thumbT, liked === 'no' && { color: '#fff' }]}>Not for me</Text>
            </TouchableOpacity>
          </View>

          <Text style={s.fbSub}>Rate this recipe</Text>
          <View style={s.starsRow}>
            {[1, 2, 3, 4, 5].map(n => (
              <TouchableOpacity key={n} onPress={() => setStars(n)} activeOpacity={0.7}>
                <Feather
                  name="star"
                  size={32}
                  color={n <= stars ? BrandColors.accent : BrandColors.textTertiary}
                  style={{ marginHorizontal: 4 }}
                />
              </TouchableOpacity>
            ))}
          </View>

          <TouchableOpacity
            onPress={submitFeedback}
            disabled={submitted || (liked === null && stars === 0)}
            activeOpacity={0.85}
          >
            <LinearGradient
              colors={submitted ? ['#444', '#666'] : Gradients.primary as [string, string]}
              start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
              style={s.fbBtn}
            >
              <Feather name={submitted ? 'check' : 'send'} size={16} color="#fff" style={{ marginRight: 8 }} />
              <Text style={s.fbBtnT}>{submitted ? 'Feedback sent' : 'Submit feedback'}</Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BrandColors.dark900 },
  scroll: { padding: Spacing.lg, paddingTop: Spacing.xl, paddingBottom: Spacing.xxl },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md, marginTop: Spacing.lg },
  backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: BrandColors.glass, borderWidth: 1, borderColor: BrandColors.glassBorder, alignItems: 'center', justifyContent: 'center' },
  aiPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: BrandColors.primaryStart, paddingHorizontal: 10, paddingVertical: 5, borderRadius: Radius.full },
  aiPillT: { color: '#fff', fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
  title: { color: BrandColors.textPrimary, ...Typography.h1, marginBottom: 4 },
  cuisine: { color: BrandColors.textSecondary, ...Typography.body, marginBottom: Spacing.md },
  stats: { flexDirection: 'row', gap: Spacing.lg, marginBottom: Spacing.md, backgroundColor: BrandColors.dark800, padding: Spacing.md, borderRadius: Radius.lg },
  stat: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  statT: { color: BrandColors.textPrimary, ...Typography.bodyBold },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: Spacing.md },
  tag: { backgroundColor: BrandColors.glass, borderWidth: 1, borderColor: BrandColors.glassBorder, paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.full },
  tagT: { color: BrandColors.textSecondary, fontSize: 11, fontWeight: '600' },
  sectionTitle: { color: BrandColors.textPrimary, ...Typography.h2, marginBottom: Spacing.sm, marginTop: Spacing.lg },
  list: { gap: Spacing.sm },
  ingItem: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  ingText: { color: BrandColors.textSecondary, ...Typography.body, flex: 1 },
  stepsTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.lg },
  progressPill: { backgroundColor: BrandColors.dark600, paddingHorizontal: 8, paddingVertical: 3, borderRadius: Radius.full },
  progressPillT: { color: BrandColors.textTertiary, fontSize: 11, fontWeight: '700' },
  progressBar: { height: 4, backgroundColor: BrandColors.dark600, borderRadius: 2, marginBottom: Spacing.md, marginTop: 4 },
  progressFill: { height: 4, backgroundColor: BrandColors.success, borderRadius: 2 },
  stepList: { gap: Spacing.md },
  stepItem: { flexDirection: 'row', gap: Spacing.md, padding: Spacing.sm, borderRadius: Radius.md, backgroundColor: BrandColors.dark800, borderWidth: 1, borderColor: BrandColors.glassBorder },
  stepItemDone: { opacity: 0.45 },
  stepCheck: { width: 28, height: 28, borderRadius: 14, backgroundColor: BrandColors.dark600, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  stepCheckDone: { backgroundColor: BrandColors.success },
  stepNumT: { color: BrandColors.primaryStart, fontWeight: '800', fontSize: 13 },
  stepText: { color: BrandColors.textSecondary, ...Typography.body, flex: 1, lineHeight: 22 },
  stepTextDone: { textDecorationLine: 'line-through', color: BrandColors.textTertiary },
  allDoneBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(52,199,89,0.12)', borderWidth: 1, borderColor: BrandColors.success, borderRadius: Radius.md, padding: Spacing.md, marginTop: Spacing.md },
  allDoneT: { color: BrandColors.success, ...Typography.bodyBold },
  bookmarkBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: BrandColors.glass, borderWidth: 1, borderColor: BrandColors.glassBorder, alignItems: 'center', justifyContent: 'center' },
  cookBtn: { flexDirection: 'row', paddingVertical: Spacing.md, borderRadius: Radius.full, alignItems: 'center', justifyContent: 'center' },
  cookBtnT: { color: '#fff', ...Typography.bodyBold, fontSize: 16 },
  shoppingBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: Spacing.sm, paddingHorizontal: Spacing.md, borderRadius: Radius.full, backgroundColor: 'rgba(255,107,53,0.08)', borderWidth: 1, borderColor: 'rgba(255,107,53,0.35)', marginTop: Spacing.xs },
  shoppingBtnT: { color: BrandColors.primaryStart, ...Typography.caption, fontWeight: '700' },
  feedback: { marginTop: Spacing.xxl, padding: Spacing.lg, backgroundColor: BrandColors.dark800, borderRadius: Radius.lg, borderWidth: 1, borderColor: BrandColors.glassBorder },
  fbTitle: { color: BrandColors.textPrimary, ...Typography.h3, marginBottom: Spacing.md, textAlign: 'center' },
  fbSub: { color: BrandColors.textSecondary, ...Typography.caption, marginTop: Spacing.lg, marginBottom: Spacing.xs, textAlign: 'center' },
  thumbsRow: { flexDirection: 'row', gap: Spacing.sm, justifyContent: 'center' },
  thumbBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, backgroundColor: BrandColors.dark600, borderRadius: Radius.full, borderWidth: 1, borderColor: BrandColors.glassBorder },
  thumbBtnActive: { backgroundColor: BrandColors.success, borderColor: BrandColors.success },
  thumbBtnActiveNo: { backgroundColor: '#A03030', borderColor: '#A03030' },
  thumbT: { color: BrandColors.textPrimary, ...Typography.bodyBold, fontSize: 13 },
  starsRow: { flexDirection: 'row', justifyContent: 'center', marginVertical: Spacing.sm },
  fbBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: Spacing.md, borderRadius: Radius.full, marginTop: Spacing.md },
  fbBtnT: { color: '#fff', ...Typography.bodyBold },
});
